### ISSUE TITLE
Make repo compatible with the standard esphome setup

### ISSUE THREAD

**Issue by drkx** [Sanderhuisman/ESPHome-Zehnder-RF#2]
Esphome has a standard way of setting up custom component repositories (see [here](https://esphome.io/components/external_components.html#external-components-git)). Is it possible to change your repository to match this way? This way it's easier to use your component, while updates are also automatically applied (see [here](https://esphome.io/components/external_components.html).

**Comment by Sanderhuisman** [comment]
I've fixed this yesterday ;)

**Comment by drkx** [comment]
Great! I already created a fork where I fixed it myself,  but then I switch back to your repo. Thank you for updating!
